POST
http://localhost:8080/api/products
@Content-Type: application/json
@Accept: application/json
{
    "name": "Mac Book Pro 15",
    "prices": 3000000,
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "category": {
        "id": 1,
        "name": "Category 3"
    }
}
%%%
# Duration: 716 ms
# POST
# http://localhost:8080/api/products
# Headers
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "name": "Mac Book Pro 15",
#     "prices": 3000000,
#     "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
#     "category": {
#         "id": 1,
#         "name": "Category 3"
#     }
# }


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sat, 24 Sep 2022 14:02:33 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [221]
{
  "status": true,
  "message": [
    "Sukses"
  ],
  "payload": {
    "id": 16,
    "name": "Mac Book Pro 15",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3000000.0,
    "category": {
      "id": 1,
      "name": "Category 3"
    },
    "suppliers": null
  }
}
