GET
http://localhost:8080/api/products?isDeleted=true
@Authorization: Basic dHJpeWFzdmlhbkBnbWFpbC5jb206c2VjcmV0
#Base64(user:password)
%%%
# Duration: 459 ms
# GET
# http://localhost:8080/api/products?isDeleted=true
# Headers
# @Authorization: Basic dHJpeWFzdmlhbkBnbWFpbC5jb206c2VjcmV0


# status 200

@Set-Cookie: JSESSIONID=B3C5F0629BB2240672DE88BD75DE61ED; Path=/; HttpOnly
@X-Content-Type-Options: nosniff
@X-XSS-Protection: 1; mode=block
@Cache-Control: no-cache, no-store, max-age=0, must-revalidate
@Pragma: no-cache
@Expires: 0
@X-Frame-Options: DENY
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 07 Oct 2022 09:58:36 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [264]
[
  {
    "id": 2,
    "name": "Mac Book Pro 14",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3.453242341E9,
    "category": {
      "createdBy": null,
      "createdDate": null,
      "updatedBy": null,
      "updatedDate": null,
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": [],
    "deleted": true
  }
]
