GET
http://localhost:8080/api/products/search/category/1

%%%
# Duration: 763 ms
# GET
# http://localhost:8080/api/products/search/category/1


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sat, 24 Sep 2022 15:03:09 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [1057]
[
  {
    "id": 14,
    "name": "Mac Book Pro 15",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3000000.0,
    "category": {
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": []
  },
  {
    "id": 15,
    "name": "Mac Book Pro 15",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3000000.0,
    "category": {
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": []
  },
  {
    "id": 16,
    "name": "Mac Book Pro 15",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3000000.0,
    "category": {
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": []
  },
  {
    "id": 2,
    "name": "Mac Book Pro 14",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": 3.453242341E9,
    "category": {
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": [
      {
        "id": 1,
        "name": "maju mapan",
        "address": "yogyakarta",
        "email": "majumapan@gmail.com",
        "products": [
          2
        ]
      },
      {
        "id": 3,
        "name": "maju mapan",
        "address": "yogyakarta",
        "email": "majumapan2@gmail.com",
        "products": [
          2
        ]
      }
    ]
  },
  {
    "id": 4,
    "name": "Mac Book Pro 15",
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
    "prices": null,
    "category": {
      "id": 1,
      "name": "Category 4"
    },
    "suppliers": []
  }
]
