PUT
http://localhost:8080/api/products
@Content-Type: application/json
@Accept: application/json
{
    "id": "1",
    "name": "Mac Book Pro 15",
    "prices": 3453242341,
    "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15"
}
%%%
# Duration: 46 ms
# PUT
# http://localhost:8080/api/products
# Headers
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "id": "1",
#     "name": "Mac Book Pro 15",
#     "prices": 3453242341,
#     "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15"
# }


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Tue, 20 Sep 2022 23:00:49 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [120]
{
  "id": 1,
  "name": "Mac Book Pro 15",
  "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
  "prices": 3.453242341E9
}
