POST
http://localhost:8080/api/categories
@Content-Type: application/json
@Accept: application/json
{
    "name": "Category 1"
}
%%%
# Duration: 22 ms
# POST
# http://localhost:8080/api/categories
# Headers
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "name": "Category 1"
# }


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sat, 24 Sep 2022 11:41:50 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [67]
{
  "status": true,
  "message": [],
  "payload": {
    "id": 4,
    "name": "Category 1"
  }
}
