PUT
http://localhost:8080/api/categories
@Authorization: Basic dHJpeWFzdmlhbkBnbWFpbC5jb206c2VjcmV0
@Content-Type: application/json
@Accept: application/json
{
    "id": 23,
    "name": "Category uuuud"
}
%%%
# Duration: 1663 ms
# PUT
# http://localhost:8080/api/categories
# Headers
# @Authorization: Basic dHJpeWFzdmlhbkBnbWFpbC5jb206c2VjcmV0
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "id": 23,
#     "name": "Category uuuud"
# }


# status 200

@Set-Cookie: JSESSIONID=F0E152C247E623990504B70DD03F27FA; Path=/; HttpOnly
@X-Content-Type-Options: nosniff
@X-XSS-Protection: 1; mode=block
@Cache-Control: no-cache, no-store, max-age=0, must-revalidate
@Pragma: no-cache
@Expires: 0
@X-Frame-Options: DENY
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Fri, 30 Sep 2022 09:49:41 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [234]
{
  "status": true,
  "message": [],
  "payload": {
    "createdBy": "triyasvian@gmail.com",
    "createdDate": "2022-09-30T09:02:26.167+00:00",
    "updatedBy": "triyasvian@gmail.com",
    "updatedDate": "2022-09-30T09:49:41.071+00:00",
    "id": 23,
    "name": "Category uuuud"
  }
}
