POST
http://localhost:8080/api/suppliers
@Content-Type: application/json
@Accept: application/json
{
    "name": "suplaipul",
    "email": "suplaipul@gmail.com",
    "address": "yogyakarta"
}
%%%
# Duration: 45 ms
# POST
# http://localhost:8080/api/suppliers
# Headers
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "name": "suplaipul",
#     "email": "suplaipul@gmail.com",
#     "address": "yogyakarta"
# }


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sun, 25 Sep 2022 11:22:27 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [143]
{
  "status": true,
  "message": [
    "Sukses"
  ],
  "payload": {
    "id": 7,
    "name": "suplaipul",
    "address": "yogyakarta",
    "email": "suplaipul@gmail.com",
    "products": null
  }
}
