POST
http://localhost:8080/api/suppliers/search/byemail
@Content-Type: application/json
@Accept: application/json
{
    "searchKey": "majumapan2@gmail.com"
}
%%%
# Duration: 1140 ms
# POST
# http://localhost:8080/api/suppliers/search/byemail
# Headers
# @Accept: application/json
# @Content-Type: application/json
# Body
# {
#     "searchKey": "majumapan2@gmail.com"
# }


# status 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sun, 25 Sep 2022 06:33:25 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive


# length: [369]
{
  "id": 3,
  "name": "maju mapan",
  "address": "yogyakarta",
  "email": "majumapan2@gmail.com",
  "products": [
    {
      "id": 2,
      "name": "Mac Book Pro 14",
      "description": "Mac Book Pro 15 Mac Book Pro 15 Mac Book Pro 15",
      "prices": 3.453242341E9,
      "category": {
        "id": 1,
        "name": "Category 4"
      },
      "suppliers": [
        3,
        {
          "id": 1,
          "name": "maju mapan",
          "address": "yogyakarta",
          "email": "majumapan@gmail.com",
          "products": [
            2
          ]
        }
      ]
    }
  ]
}
